create DATABASE dhruvivirani;
use dhruvivirani;
CREATE TABLE students (ROLL_NO int NOT NULL,name varchar(20), surname varchar(20));
CREATE TABLE INFORMATION(Address varchar(40), email_id varchar(30) UNIQUE, phone_no varchar(10));
CREATE TABLE UNIVERSITY(field varchar(20),branch varchar(20),country varchar(20), city varchar(20));
CREATE TABLE SUBJECT1(subject_name varchar(20),marks double, subject_id int(7),subject_teacher varchar(20));
CREATE TABLE PLACEMENTS(company_name varchar(30),track varchar(20),Sub_track varchar(20),global_id int(6) NOT NULL);
describe placements;
DROP TABLE INFORMATION;
ALTER TABLE UNIVERSITY RENAME COLUMN field to stream;
describe UNIVERSITY; 
insert into students values(1001,'aman','tiwari'),(1002,'shubham','sinha'),(1003,'jigar','dhankara');
insert into information values('abc','gmail',123),('def','yahoo',456),('ghi','firefox',789);
insert into university values('Engineering','EC','INDIA','Ahmedabad'),('Engineering','IT','INDIA','Pune'),('MCA','CE','INDIA','Surat');
insert into subject1 values('OOPs',90,3711090,'Khushi'),('Maths',87,3420196,'Dhruvi'),('SOCIAL SCIENCE',85,3261829,'JYOTI');
insert into placements values('Einfo','IA','python',158317),('Argusoft','IA','Python',158320),('Odoo','IA','Python',158341);
alter table placements drop column joining_date;
delete from university where stream="Engineering";
select * from university;
update university SET stream='engineering'where branch='CE';
describe students;
create table Client_info (Client_no Varchar(6), Name varchar(20) NOT NULL,City varchar(15),pincode NUMERIC(6), State varchar(20), Bal_due numeric(10,2));
insert into client_info values(1,'joy','pune',345216,'maharshtra','12.2');
insert into client_info values(2,'bob','surat',352681,'gujarat',1.9);
insert into client_info values(2,'NULL','surat',352681,'gujarat',1.9);
desc client_info;
create table brand (id integer, brandname varchar(40) unique, size varchar(30));
insert into brand(id,brandname,size) values(1,'pantaloons',38),(1,'allensolly',38);
insert into brand(id,brandname,size) values(1,'raymond',38),(1,'allensolly',38);
desc brand;
select * from brand;
alter table students modify column ROLL_NO int check(ROLL_NO>1000);
insert into students values(1001,'aman','tiwari'),(1002,'shubham','sinha'),(1003,'jigar','dhankara');
insert into students values(1004,'dhruvi','virani');
select * from students;
insert into students(ROLL_NO, name, surname) values(1005,'jyoti','prajapati');
alter table students modify column ROLL_NO INT default '1005';
insert into students(name,surname) values('dhruvi','virani');
create table animals(id int not null auto_increment, name char(30) not null, primary key(id));
insert into animals (name) values('tiger'),('dog'),('cat'),('duck'),('lion');
select*from animals;
create table shirts(id int primary key auto_increment, name varchar(20),size ENUM('small','medium','large'));
insert into shirts(id,name,size) values(1,'tshirt','medium'),(2,'shirts','small');
insert into shirts(id,name,size) values(3,'formal','large');
select*from shirts;
create table person1(id varchar(10) primary key,name varchar(20), surname varchar(20));
insert into person1(id,name,surname) values(1,'abc','singhania'),(2,'xyz','malhotra');
desc person1;
create table orders(order_id int primary key, order_num int not null,FK_person_id int, foreign key(FK_person_id) references person1(id));
create table orders1(order_id int primary key, order_num int not null,FK_person_id int, foreign key(FK_person_id) references person1(id));
desc orders;
create table persons(id varchar(10) primary key,name varchar(20), surname varchar(20));
desc persons;
insert into persons(id,name,surname) values(1,'abc','singhania'),(2,'xyz','malhotra');
create table order3(order_id int primary key, order_num int not null, order_name varchar(30),FK_person_id int , foreign key(FK_person_id) references persons(id));
drop table person1;
drop table persons;
drop table person;
create table person(person_id int primary key, name varchar(30), surname varchar(30));
insert into person(person_id,name,surname) values(4,'abc','singhania'),(6,'xyz','malhotra');
desc person;
select * from person;
create table menu(order_id int primary key, order_num int not null, FK_person_id int, foreign key(FK_person_id) references person(person_id) on delete cascade on update cascade);
insert into menu(order_id,order_num) values(3,10);
insert into menu(order_id,order_num,FK_person_id) values(5,10,6);
set foreign_key_checks=1;
select * from menu;
delete from person where name='abc';
select * from person;
drop table menu;
drop table person;
update person set person_id=7 where person_id=6;
